const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const path = require('node:path');
const { test } = require('node:test');
const rules = require('../attribution-rules.json');
const replay = require('./attribution-replay.json');
const { normalize, evaluateAttribution, checkPullRequest } = require('./attribution-guard.cjs');

const root = path.resolve(__dirname, '../..');
const identity = { name: 'BichengWang', email: 'bichengwang17@gmail.com' };
const commit = (message, author = identity, committer = identity, sha = 'head') => ({
  sha, commit: { message, author, committer },
});
const clean = {
  actor: 'BichengWang', branch: 'BichengWang/checks', title: 'Require checks', body: '',
  commits: [commit('Require checks')],
};
const evaluate = input => evaluateAttribution(rules, { ...clean, ...input });

test('replay the last 30 merged PRs at the recorded base', async t => {
  const history = execFileSync('git', [
    'log', '-30', '--first-parent', replay.base_sha, '--format=%H%x09%s',
  ], { cwd: root, encoding: 'utf8' }).trim().split('\n');
  assert.equal(replay.pull_requests.length, 30);
  assert.deepEqual(history.map(line => Number(line.match(/\(#(\d+)\)$/)[1])),
    replay.pull_requests.map(pr => pr.number));
  const deniedBranches = new Set([160, 175, 186, 187, 188]);

  for (const [index, pr] of replay.pull_requests.entries()) {
    const denied = deniedBranches.has(pr.number);
    await t.test(`#${pr.number} ${pr.branch}: ${denied ? 'reject branch' : 'pass'}`, () => {
      const sha = history[index].split('\t')[0];
      const [name, email, committerName, committerEmail, message] = execFileSync('git', [
        'show', '--no-patch', '--format=%an%x00%ae%x00%cn%x00%ce%x00%B', sha,
      ], { cwd: root, encoding: 'utf8' }).split('\0');
      const commits = [commit(message, { name, email },
        { name: committerName, email: committerEmail }, sha)];
      const input = { ...pr, title: message.split('\n')[0], commits };
      assert.deepEqual(evaluate({ ...input, branch: 'history/replay' }).errors, []);
      const result = evaluate(input);
      assert.equal(result.errors.length, denied ? 1 : 0);
      if (denied) assert.match(result.errors[0], /^Head branch:/);
    });
  }
});

test('reject forbidden attribution including normalized disguises', async t => {
  const cases = [
    ['branch prefix', { branch: 'codex/x' }],
    ['branch substring', { branch: 'BichengWang/Claude-sdk' }],
    ['branch digits', { branch: 'feature/gpt-4-update' }],
    ['commit trailer', { commits: [commit('Change\n\nCo-authored-by: Claude <noreply@anthropic.com>')] }],
    ['body attribution', { body: 'Generated with [Claude Code]' }],
    ['title attribution', { title: 'Generated by Codex' }],
    ['zero-width trailer', { commits: [commit('Co-authored-by: Cl\u200Baude <person@example.com>')] }],
    ['bidi trailer', { commits: [commit('Co-authored-by: Cl\u202Eaude <person@example.com>')] }],
    ['fullwidth trailer', { commits: [commit('Co-authored-by: Ｃｌａｕｄｅ <person@example.com>')] }],
    ['fullwidth branch', { branch: 'feature/Ｃｏｄｅｘ' }],
    ['vendor email trailer', { body: 'Co-authored-by: Developer <person@openai.com>' }],
    ['session marker', { body: 'claude-session: 123' }],
    ['robot marker', { body: '\u{1F916}' }],
    ['author email', { commits: [commit('Change', { ...identity, email: 'person@anthropic.com' })] }],
    ['committer email', { commits: [commit('Change', identity, { ...identity, email: 'person@openai.com' })] }],
    ['author name', { commits: [commit('Change', { ...identity, name: 'Claude Code' })] }],
    ['committer name', { commits: [commit('Change', identity, { ...identity, name: 'Ｃｏｄｅｘ' })] }],
    ['earlier commit', { commits: [commit('Generated with Codex'), commit('Clean head')] }],
  ];
  for (const [label, input] of cases) {
    await t.test(label, () => assert.ok(evaluate(input).errors.length > 0));
  }
});

test('normalize every specified invisible control range', () => {
  const controls = [0x200B, 0x200C, 0x200D, 0x200E, 0x200F, 0x202A, 0x202B,
    0x202C, 0x202D, 0x202E, 0x2060, 0x2061, 0x2062, 0x2063, 0x2064,
    0x2066, 0x2067, 0x2068, 0x2069, 0xFEFF];
  for (const code of controls) {
    const text = `Co-authored-by: Cl${String.fromCodePoint(code)}aude <person@example.com>`;
    assert.equal(normalize(text), 'Co-authored-by: Claude <person@example.com>');
    assert.ok(evaluate({ body: text }).errors.length);
  }
  assert.equal(normalize('Ｃｌａｕｄｅ'), 'Claude');
});

test('allow real identities and warn on ordinary vendor prose', () => {
  for (const email of ['bichengwang17@gmail.com', '31808103+BichengWang@users.noreply.github.com']) {
    const result = evaluate({
      title: 'Update the Claude integration', body: 'Compare Codex and existing tooling.',
      commits: [commit('Document Claude integration', { name: 'Bicheng (Kenneth)', email },
        { name: 'GitHub', email: 'noreply@github.com' })],
    });
    assert.deepEqual(result.errors, []);
    assert.ok(result.warnings.some(warning => warning.startsWith('PR title:')));
    assert.ok(result.warnings.some(warning => warning.startsWith('PR body:')));
    assert.ok(result.warnings.some(warning => warning.startsWith('Commit head message:')));
  }
});

function apiRun({ pr = {}, commits = clean.commits, current = {} } = {}) {
  const initial = {
    number: 1, head: { sha: 'head', ref: clean.branch }, user: { login: clean.actor },
    title: clean.title, body: clean.body, commits: commits.length, ...pr,
  };
  const calls = [];
  const annotations = { errors: [], warnings: [], failures: [], info: [] };
  let reads = 0;
  const github = {
    rest: { pulls: {
      get: async params => {
        calls.push(['get', params]);
        return { data: reads++ === 0 ? initial : { ...initial, ...current } };
      },
      listCommits: () => {},
    } },
    paginate: async (endpoint, params) => {
      assert.equal(endpoint, github.rest.pulls.listCommits);
      calls.push(['paginate', params]);
      return commits;
    },
  };
  const core = {
    error: message => annotations.errors.push(message),
    warning: message => annotations.warnings.push(message),
    setFailed: message => annotations.failures.push(message),
    info: message => annotations.info.push(message),
  };
  const context = {
    repo: { owner: 'BichengWang', repo: 'aai' }, actor: 'BichengWang',
    payload: { pull_request: { number: 1, head: { sha: 'head' } } },
  };
  return { run: () => checkPullRequest({ github, context, core, rules }), calls, annotations };
}

test('load all API commits and emit warnings without failure', async () => {
  const commits = Array.from({ length: 201 }, (_, i) =>
    commit('Compare Claude integrations', identity, identity, i === 200 ? 'head' : `${i}`));
  const api = apiRun({ commits, pr: { title: 'Compare Codex integrations' } });
  await api.run();
  assert.equal(api.calls[1][0], 'paginate');
  assert.deepEqual(api.calls[1][1], { owner: 'BichengWang', repo: 'aai', pull_number: 1, per_page: 100 });
  assert.equal(api.annotations.warnings.length, 202);
  assert.deepEqual(api.annotations.failures, []);
});

test('fail when any API commit has forbidden attribution', async () => {
  const api = apiRun({ commits: [commit('Co-authored-by: Claude <person@example.com>', identity, identity, 'first'),
    commit('Clean head')] });
  await api.run();
  assert.equal(api.annotations.errors.length, 1);
  assert.equal(api.annotations.failures.length, 1);
});

test('fail closed on incomplete API results and changing metadata', async t => {
  for (const input of [
    { pr: { commits: 251 } },
    { commits: [commit('Change', identity, identity, 'old-head')] },
    { pr: { head: { sha: 'new-head', ref: clean.branch } } },
    { current: { head: { sha: 'new-head', ref: clean.branch } } },
    { current: { title: 'Changed title' } },
    { current: { body: 'Changed body' } },
  ]) {
    await t.test(JSON.stringify(input), async () => {
      const api = apiRun(input);
      await api.run();
      assert.equal(api.annotations.failures.length, 1);
    });
  }
});

test('exempt a dependabot PR by its author even when another user triggers it', async () => {
  const api = apiRun({ pr: { user: { login: 'dependabot[bot]' }, head: { sha: 'head', ref: 'codex/x' },
    body: 'Generated with [Claude Code]' } });
  await api.run();
  assert.equal(api.calls.length, 1);
  assert.deepEqual(api.annotations.failures, []);
  assert.deepEqual(evaluate({ actor: 'dependabot[bot]', branch: 'codex/x', body: 'Generated with Codex' }),
    { errors: [], warnings: [] });
});
